### ISSUE TITLE
Simple included template is invisible

### ISSUE THREAD

**Issue by mmnosek** [Juicy/juicy-composition#2] opened 2016-10-25 14:26 UTC
I've tried to create the simplest template as it's possible and include it using `starcounter-composition`. Template:

```
<template>
    <template is="dom-bind">
         Hello!
    </template>   
</template>
```

But there is no result in rendered site. I found out that I have to put my text into some element like `<span>Hello!</span>` to make it visible. It is a bit confusing, so I think that `starcounter-composition` should work in one of two ways:
- Redistribute my text without any additional element
- Show some warning in console that I've made an error

cc @tomalec @warpech

**Comment by tomalec** [comment] 2016-10-25 15:33
It works like this by design, as we do not distribute/compose text nodes, only 'real' elements
(excluded are: text, comment, template, script, link).

> 1 - Redistribute my text without any additional element

It could be a little bit problematic to create and reference such anonymous slots. If I remember the spec correctly, in Shadow DOM text nodes are distributed to the _default_ slot. So I would say, if we want Text nodes to work putting them altogether into _default_ slot is the only way.

So the question is what would be more confusing?

> 2 - Show some warning in console that I've made an error

Should be easily doable, the question is performance, as we will need to show error/warning on every mutation per each filtered element (empty/whitespace-only text nodes included)

I could propose also the third way

 3 - Do not filter elements and distribute templates,scripts,etc. into default slot.
Simplifies the code and behavior, but makes it problematic for editors/designers, as they will see many slots for non-visible elements .

@warpech WDTY?

@Mnosek " the simplest template as it's possible" would look like:

``` html
<template>
    Hello!
</template>
```

**Comment by warpech** [comment] 2016-11-03 17:47
> 2 - Should be easily doable, the question is performance, as we will need to show error/warning on every mutation per each filtered element (empty/whitespace-only text nodes included)

How about doing it only on load event, without mutation observer? Similarly to how you show this warning: https://github.com/Juicy/imported-template/blob/43c4048d7a5ecd96288f657fa3248548e1af8180/imported-template.html#L91

Actually I think that we would not mind fixing it in `imported-template` instead of `juicy-composition`.

> 3 - Do not filter elements and distribute templates,scripts,etc. into default slot.
> Simplifies the code and behavior, but makes it problematic for editors/designers, as they will see many slots for non-visible elements .

So we actually filter out nodes that are not elements? I thought that slots can only distribute elements. Could you set up some prototype of how does it work?

**Comment by tomalec** [comment] 2016-11-04 08:09
We do filter elements https://github.com/Juicy/juicy-composition/blob/gh-pages/juicy-composition.html#L274
Do you remember that? ;) it was in `juicy-tile-*`

I think moving it to `imported-template` is a really bad idea. Why do you think we should not stamp scripts, comments, inline text etc?

> I thought that slots can only distribute elements. Could you set up some prototype of how does it work?

Slots can distribute everything. The only problem with text is that you cannot declaratively assign slot name, so they end up in default slot.
http://jsbin.com/bejude/1/edit?html,output

Even CSS Grid Layout works with inline text.

That's why I think we should no longer filter text nodes. So only visual editor will somehow need to notify the fact that all text nodes will be distributed into single default slot.

The regular HTML input designed for developers should embrace full freedom of Shadow DOM.

**Comment by mmnosek** [comment] 2017-12-27 11:17
@warpech @tomalec year passed - can we take a decision on this or should it be abandoned as `juicy-composition` is deprecated? What replaces it? Maybe it's relevant to this "new thing" as well?

**Comment by tomalec** [comment] 2017-12-28 13:53
The new thing is just `starcounter-include` (could be `declarativeshadow-dom` itself in future).

The current behavior is:
1. Text nodes are distributed in _default slot_, if provided.
    _default slot_ is provided if there is no custom compostion (just `declarative-shadow-dom`s or nothing at all) by Starcounter, either by HTML merger (`d-s-d`s) or by `starcounter-include` (nothing). It could but does not have to be used in matching custom composition.
2. There is no console message nor error, as I consider it could be desired behavior. In general I would stick to the platform and reduce SC magic on top of Shadow DOM, to simplify explanations and entire flow.
3. We removed any filtering magic, everything w/0 slot name would be distributed in default slot, as per spec.


Is that fine for you?

**Comment by warpech** [comment] 2017-12-29 15:37
In other words - the current behavior of `starcounter-include` is that the example from OT renders the text `Hello!` as expected unless someone explicitly removes the default slot in the composition.

We think that we don't have to explain it because right now we follow the default behavior as in the spec.

I assume this must be fine. If it is not, please open a new issue in RebelsLounge. If you think something has to be clarified in the docs, please open a new issue in Docs. 

Thanks for following this!

Closing as solved elsewhere (in `starcounter-include`).

**Closed as completed by warpech** 2017-12-29 15:37 UTC

**Comment by mmnosek** [comment] 2018-01-02 09:23
Thanks guys for the explanation! I agree that this is expected behavior, I'm happy with this!
